### ISSUE TITLE
Unable to load pre-trained robust models for CIFAR10 L2-norm (ResNet50)

### ISSUE THREAD

**Issue by evankravitz-berk** [MadryLab/robustness#8] opened 2019-10-10 00:18 UTC
I am unable to load some of the pretrained robust models for CIFAR10 L2-norm (ResNet50). I have downloaded the model files directly from the dropbox links and have placed them into the `/home/ubuntu/Research/DomainShift_Experiment` directory. Here's the code that I'm running:

```
from robustness.model_utils import make_and_restore_model
from robustness.datasets import CIFAR

 
model_paths_dict = {0.0: "nat.pt",
                   0.25 : "l2_0_25.pt",
                   0.5: "l2_0_5.pt",
                   1.0: "l2_1_0.pt",
                   }

DS = "ds"
NORMAL = "normal"

base_path = '/home/ubuntu/Research/DomainShift_Experiment/cifar_'

models = {}
for eps in model_paths_dict:
    # Load Madry's models
    ds = CIFAR('/tmp')
    print(model_paths_dict[eps])
    model, _ = make_and_restore_model(arch='resnet50', dataset=ds,
                 resume_path=base_path+model_paths_dict[eps])
    model.eval()

    models[eps] = model   
```

Here's the output I get:

```
nat.pt
=> loading checkpoint '/home/ubuntu/Research/DomainShift_Experiment/cifar_nat.pt'
=> loaded checkpoint '/home/ubuntu/Research/DomainShift_Experiment/cifar_nat.pt' (epoch 190)
l2_0_25.pt
=> loading checkpoint '/home/ubuntu/Research/DomainShift_Experiment/cifar_l2_0_25.pt'

Traceback (most recent call last):
  File "test_loading_models.py", line 22, in <module>
    resume_path=base_path+model_paths_dict[eps])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/robustness/model_utils.py", line 71, in make_and_restore_model
    checkpoint = ch.load(resume_path, pickle_module=dill)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/serialization.py", line 573, in _load
    result = unpickler.load()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/dill/_dill.py", line 472, in load
    obj = StockUnpickler.load(self)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cox/utils.py", line 134, in __setstate__
    self.params = x
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cox/utils.py", line 110, in __setattr__
    self.params[x.lower()] = v
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cox/utils.py", line 101, in __getattr__
    if k not in self.params:
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cox/utils.py", line 101, in __getattr__
    if k not in self.params:
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/cox/utils.py", line 101, in __getattr__
    if k not in self.params:
  [Previous line repeated 325 more times]
RecursionError: maximum recursion depth exceeded
```

This same error occurs for when epsilon = 1. The only models that I can successfully load are for epsilon = 0, 0.5

**Comment by andrewilyas** [comment] 2019-10-10 01:46
Hi Evan,

It seems your download might have been corrupted somehow. In particular, the following series of commands works for me:
```
wget https://www.dropbox.com/s/2qsp7pt6t7uo71w/cifar_l2_0_25.pt\?dl=1
mv cifar_l2_0_25.pt\?dl=1 eps25.pt
python
>>> from robustness import datasets, model_utils
>>> cifar = datasets.CIFAR('/tmp/')
>>> m, _ = model_utils.make_and_restore_model(arch='resnet50', dataset=cifar, resume_path='cifar_l2_0_25.pt')
=> loading checkpoint 'cifar_l2_0_25.pt'
=> loaded checkpoint 'cifar_l2_0_25.pt' (epoch 105)
```

Feel free to reopen the issue if running the same set of commands does not yield the same result.

**Comment by evankravitz-berk** [comment] 2019-10-10 05:07
This exact sequence of commands gives me the exact same error as I got before.

**Comment by lengstrom** [comment] 2019-10-10 18:13
Can you list your versions of pytorch, python, torchvision, dill? Also what
OS?

**Comment by iamgroot42** [comment] 2019-10-17 17:30
I get the same error as well. 

Ubuntu: 16.04
Python: 3.6.5
Pytorch: 1.3
Torchvision: 0.4.1
Dill: 0.3.1.1

**Comment by andrewilyas** [comment] 2019-10-18 14:42
@iamgroot42 Can you try running the same commands in the following environment?

Pytorch==1.1.0
Torchvision==0.3.0
Dill==0.2.9

If this ends up being the problem I'll upgrade these packages and regenerate the checkpoint files

**Comment by iamgroot42** [comment] 2019-10-18 15:37
This worked for me. Thanks @andrewilyas !

**Comment by andrewilyas** [comment] 2019-10-18 18:54
@evankravitz-berk This will probably fix your issue as well. I'll make a note of this in the README and try to figure out if its possible to re-encode them somehow. Closing for now!

**Comment by evankravitz-berk** [comment] 2019-10-18 22:39
We are still running into this problem: I ran the same commands with the right package versions but I still get the error. 

```
ubuntu 16.04

pytorch: 1.1.0
torchvision: 0.3.0
dill: 0.2.9 
robustness: 1.0.post1  

python: 3.6.5 
cox: 0.1 
```
Here's the error I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/robustness/model_utils.py", line 71, in make_and_restore_model
    checkpoint = ch.load(resume_path, pickle_module=dill)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py", line 574, in _load
    result = unpickler.load()
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/cox/utils.py", line 134, in __setstate__
    self.params = x
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/cox/utils.py", line 110, in __setattr__
    self.params[x.lower()] = v
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/cox/utils.py", line 101, in __getattr__
    if k not in self.params:
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/cox/utils.py", line 101, in __getattr__
    if k not in self.params:
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/cox/utils.py", line 101, in __getattr__
    if k not in self.params:
  [Previous line repeated 325 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by evankravitz-berk** [comment] 2019-10-24 21:18
@andrewilyas - fixing the versions did not help. Any other suggestions?

Not sure if this helps, but we're running this on an EC2 AWS instance.

**Comment by andrewilyas** [comment] 2019-10-25 17:23
Hi @evankravitz-berk I finally was able to reproduce this issue (although somehow with mixed/inconsistent results). I pushed an update to the cox library (``0.1.post1``) that fixed it on an EC2 instance I set up---can you try updating to that?

**Comment by iamgroot42** [comment] 2019-10-26 00:22
I got the same error for L2 trained on eps=0.25; I think it's a problem specific to this model

**Comment by andrewilyas** [comment] 2019-10-26 21:55
@iamgroot42 Can you try the fix above?

**Comment by iamgroot42** [comment] 2019-10-26 22:00
I got a cox-specific error (only for L2_0_25; everything else works just fine as before):

`File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 193, in _run_module_as_main                                                                                                                                        "__main__", mod_spec)`
                                                                                                                                                                                                                      `File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 85, in _run_code                                                                                                                                                   exec(code, run_globals) `                      
                                                                                                                                                                                             `File "/home/ubuntu/phd/robustness/robustness/main.py", line 114, in <module>                                                                                                                                                                   final_model = main(args, store=store)`
                                                                                                                                                                                                     `File "/home/ubuntu/phd/robustness/robustness/main.py", line 50, in main                                                                                                                                                                        dataset=dataset, resume_path=args.resume) `
                                                                                                                                                                                                 `File "/home/ubuntu/phd/robustness/robustness/model_utils.py", line 71, in make_and_restore_model                                                                                                                                               checkpoint = ch.load(resume_path, pickle_module=dill)  `  
                                                                                                                                                                                  `File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py", line 426, in load                                                                                                                           return _load(f, map_location, pickle_module, **pickle_load_args)`
                                                                                                                                                                          `File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/serialization.py", line 613, in _load                                                                                                                          result = unpickler.load()   `     
                                                                                                                                                                                                          `File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/dill/_dill.py", line 472, in load                                                                                                                                    obj = StockUnpickler.load(self)  `   
                                                                                                                                                                                                       `File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/cox/utils.py", line 141, in __setstate__                                                                                                                             self.params = x            `
                                                                                                                                                                                                                `File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/cox/utils.py", line 111, in __setattr__                                                                                                                              super().__setattr__(x, b)       `    
                                                                                                                                                                                                     `NameError: name 'b' is not defined`

**Comment by andrewilyas** [comment] 2019-10-27 23:56
@iamgroot42 @evankravitz-berk sorry, a mistake on my part. Can you try updating cox again? The version should be `0.1.post2`

**Comment by evankravitz-berk** [comment] 2019-10-29 21:37
@andrewilyas Updating the `cox` library seems to have solved the issue. Thanks!

**Comment by andrewilyas** [comment] 2019-10-30 14:19
great!

**Closed by andrewilyas** 2019-10-30 14:19 UTC
